# Generated by Django 3.1.7 on 2021-04-20 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardealer',
            name='experience',
        ),
        migrations.AddField(
            model_name='cardealer',
            name='detail',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
